### ISSUE TITLE
Callbacks not called after looking up non-existing key

### ISSUE THREAD

**Issue by andres-liiver** [Cylix/cpp_redis#86] opened 2017-07-03 21:17 UTC
Hi, are the callbacks not supposed to be called when looking up a key that doesn't exist?

For example:

```cpp
cpp_redis::redis_client redisClient;
redisClient.connect();

redisClient.get("doesnotexist", [](cpp_redis::reply& reply) {
    std::cout << reply << std::endl; // Never executed
});

redisClient.sync_commit(std::chrono::milliseconds(100));
```

Code is in a try/catch block and no exception is thrown either.

Also, when reusing the open connection and not instantiating a new client, subsequent get calls will not have their callbacks invoked anymore even if the key does exist. Example:

```cpp
cpp_redis::redis_client redisClient;
redisClient.connect();

redisClient.get("doesnotexist", [](cpp_redis::reply& reply) {
    std::cout << reply << std::endl; // Never executed
});

redisClient.sync_commit(std::chrono::milliseconds(100));

redisClient.get("existingkey", [](cpp_redis::reply& reply) {
    std::cout << reply << std::endl; // Also never executed
});

redisClient.sync_commit(std::chrono::milliseconds(100));
```

I previously used the future_client, but looking up a non-existing key caused future.get() to block indefinitely.

EDIT: Actually, instantiating a new client every time does not fix it either.

**Comment by Cylix** [comment] 2017-07-04 00:08
Hi,

This sounds to be a bug, there is no reason the callbacks should not be called.
If the key does not exist, it should call the callback with a null reply.

I tried on my side but I was not able to reproduce the bug.
Would you mind providing me additional information: what platform are you using (windows/debian/mac/...)? Which version of cpp_redis are you using?

If you modify the [provided example](https://github.com/Cylix/cpp_redis/blob/master/examples/redis_client.cpp) to only get a non-existing key, does it also fail on your side?

Best

**Comment by andres-liiver** [comment] 2017-07-04 07:09
Linux 4.9.31 armv7l
Redis server v=3.2.9
g++ (GCC) 7.1.1 20170516
cpp_redis v3.5.3
tacopie v2.4.4

I found out that the callbacks are not called because of sync_commit timeout.
I modified the example to this:

```cpp
#include <cpp_redis/cpp_redis>
#include <iostream>

int main() {
  cpp_redis::redis_client client;

  client.connect("127.0.0.1", 6379, [](cpp_redis::redis_client&) {
    std::cout << "client disconnected (disconnection handler)" << std::endl;
  });

  client.get("doesnotexist", [](cpp_redis::reply& reply) {
    std::cout << "get reply: " << reply << std::endl;
  });

  client.sync_commit();
  return 0;
}
```

Compiled like this:
```
g++ test.cpp -o test --std=c++14 -pthread -lpthread -lcpp_redis -ltacopie
```

sync_commit never returns which is probably also why future.get() would block indefinitely.
`client list` in redis-cli while it's blocked in sync_commit shows that the test client is connected.

It works as expected when changing the key to an existing one. Also, when putting a get of an existing key before the non-existing one, I see the output of the existing key and then it hangs in sync_commit.

**Comment by andres-liiver** [comment] 2017-07-04 20:40
Changing [this line](https://github.com/Cylix/cpp_redis/blob/master/includes/cpp_redis/builders/integer_builder.hpp#L55) from `char m_negative_multiplicator;` to `int16_t m_negative_multiplicator;` fixes it.

**Comment by Cylix** [comment] 2017-07-07 06:18
Hi,

Thanks a lot for your investigation and apologize for the late reply!

I'm not really sure why this overflow would happen, this is pretty weird?
Technically, -1 should be represented as 11111111 in binary in the char.
Looks like it either get interpreted as an unsigned value at some point (resulting into 255 * 1 instead of -1 * 1 in get_integer) or it get converted to a bigger type but the conversion is poorly done (lets say it get converted to int64t but instead of having 1111....111111 we got 00000....11111111 by filling missing bits with zeros instead of ones?).

Feels like something is going wrong, I'll try to reproduce it and check the generated assembly code, I would be curious to understand what is going on.

Anyway, I will apply the fix, probably with a int64_t instead of a int16_t.
Maybe there is some issues with large arrays on some architectures when doing the multiplication, so safer to keep same type for both operands I guess until I can get more clues.

Thanks again for reporting and investigating, that's really cool!

Best :)

**Comment by Cylix** [comment] 2017-07-07 06:34
I applied the fix, so I close this issue though you can re-open it if necessary.
If I find more explanations when doing some testing on my side, I'll post them here.

Best!

**Closed by Cylix** 2017-07-07 06:34 UTC
