### ISSUE TITLE
Problems with HA

### ISSUE THREAD

**Issue by Alejandro131** [Cylix/cpp_redis#137] opened 2017-11-24 10:00 UTC
Hi Cylix,

Needless to say your library is good and the fact that you resolve issues quickly means that it will soon converge to a very stable release.

I'm sorry for the vague issue title, but since it includes several things, it would be easier to explain them here than in the title.

I'm trying to configure HA redis setup and use it within our project, but it seems that there are some issues with the library. The setup I have is 1 redis master, 1 redis slave and 3 redis sentinel and everything has been tested outside of the project and works okay. I'm pasting a sample code for you to reproduce:

```
#include <cpp_redis/cpp_redis>
#include <iostream>
#include <chrono>
#include <thread>

using namespace std;

int main(void) {
	string masterName = "master";
	string key = "test";

	cpp_redis::client redis;

	redis.add_sentinel("127.0.0.1", 26379, 1000);
	redis.connect(masterName, nullptr, 1000, 1, 1000);
	redis.select(0);
	redis.sync_commit();

	while (true)
	{
		cout << endl;

		string master_host = "";
		size_t master_port = 0;

		redis.get_sentinel().get_master_addr_by_name(masterName, master_host, master_port);

		cout << "current master is " << master_host << " " << master_port << endl;

		cout << "pre get; ";
		auto res = redis.get(key);
		cout << "pre sync_commit; ";
		redis.sync_commit();
		cout << "pre future get; ";
		auto result = res.get();
		cout << "[" << key << "] = [" << result << "]" << endl;
		cout << endl;

		this_thread::sleep_for(chrono::milliseconds(3000));
	}

	return 0;
}
```

The first issue that I'm experiencing is probably somewhere between the reconnection logic and response handling logic. If I execute a 'DEBUG sleep 30' or 'SHUTDOWN' command on the redis master (which leads to a failover procedure and election of the slave to the new master) the program hangs (probably either to a deadlock or no timeout on the future/socket read/write logic). In the case of debug sleep, it continues to run after 30 seconds (when the redis server becomes active), in the case of shutdown, it never resumes normally and has to be forcefully killed.

This leads me to the second issue. Even if the client continues to run in the first case, it is connected to the same redis server (which is now a slave) and all writes would be useless (since it needs to write to the master). I see in your reconnection logic that you have a case for sentinel and trying to get the current master, which should probably work, but I've tested in cases where I have a connection state callback function and it prints that the status has changed to dropped and then sleeping and then doesn't change (but the sleep time is only 1 second) so I think that it is probably a deadlock and waiting situation.

The problem is that even if I have a separate application detect the master change and send a signal or some other way to get the message to this application it would still be useless as it returns to the hanged state and can't process a reconnection or something else.

Ideally I would like to have a global timeout on operations or some way to fix the above issue (if a timeout isn't appropriate). Probably if the first issue is fixed, the second would resolve itself.

Best Regards,
Alex

**Comment by Cylix** [comment] 2017-11-26 01:45
Hi,

First, thanks for reporting issues: as you said, it really helps to make this library get better over the time and maybe to become a reference in the future :)

I pushed a fix on master that should solve your issues.
I did not use your test, but I used a custom HA test (currently pushed in the repository as the HA example) and got the same issues as you reported. After the fix, everything works fine.

I'm closing this issue, but do not hesitate to re-open it if you happen to find out that there are still some issues.
If you happen to have the time to try the fix and that everything works fine, feel free to let me know in comments, that would help me to confirm that the problem is fixed :)

Thanks again!

Best

**Closed by Cylix** 2017-11-26 01:45 UTC
Labels: bug, WIP

**Comment by Alejandro131** [comment] 2017-11-27 09:29
Hi,

I tested the fix and it works when I issue a 'SHUTDOWN' command, but doesn't for 'DEBUG SLEEP'. I guess that technically this shouldn't be a problem, but if a server is unresponsive, the Sentinel will initiate a failover and by the time it responds, it would be a slave. I can manage that from a separate process / thread that constantly tries to connect and finds out the current master and reports it back, so this shouldn't be a problem. In the future if you want to have a solid implementation for this in the library, you can either reconnect to a sentinel to find out who the master is, or have a subscriber to one of the sentinels and listen for the master change event.

One question that I would like to ask is whether I need 2 network workers globally, or do I need 2 network workers per redis connection? I'm asking this because on some processes I'm using a redis client and subscriber simultaneously or 2 redis clients and can't time it so that the 2 are being used and the server stops, but if this happens to occur I would like to be prepared for it.

The last thing I would like to mention is that the network worker number needs to be set after fork as well, because of the deletion of the io service. I know this from what we've debugged and communicated, but you might want to consider adding a forking example when you have the time, so that new users who might need it, will have it ready to go, since it requires extra lines of code that might not be so easy to find.

Best

**Comment by Cylix** [comment] 2017-11-28 05:44
Hi,

Thanks for getting back to me!

For the sleep case, sounds reasonable to add support for that, but I can't give you any timeline about it as it requires quite some critical change to integrate some timeout somewhere in the library (time to design/impl/test).

For the number of workers, I will make it clearer in the documentation.
Basically, you would need 1+n workers where n is the number HA client/subs you got.
The main reason is that the reconnection process of the sentinels is using some blocking operations (sync_commit) from within the workers (when a worker is executed after a disconnection has been detected). The sync operations have been chosen over async operations to ensure thread safety and data integrity when some other threads keep trying to send commands to the disconnected clients while the client is being reconnected and possibly replays the commands.
Probably an improvement in the future would be to switch these sync operations to async to decrease the number of workers if it appears to be an issue.
In any case, documentation needs to be clarified, thanks for asking :)

Good point concerning the fork, will update!

Let me know if you have any other questions/feedbacks and thanks again for helping with this project!

Best

**Comment by Alejandro131** [comment] 2017-11-28 07:36
Hi,

Thank you for supporting this project so actively and resolving issues so quickly!

The sleep case as I mentioned isn't such a big problem for me, so I won't be expecting an update for it any time soon, thank you for considering it though.

For the number of workers in that case I will just set it to something high (like 5 maybe) at startup so that if I have 4 redis connections (which is probably the maximum I will have at a given time) HA would work properly. I thought it might be that every client needed 2 workers so that all of them could reconnect simultaneously, but since this isn't the case, this is even better.

No problem for the updates and I'm glad that I could be of help for the project as it is helping me in mine 😉 

Best
