### ISSUE TITLE
After fork redis doesn't work in the child process

### ISSUE THREAD

**Issue by Alejandro131** [Cylix/cpp_redis#130] opened 2017-11-03 15:41 UTC
Hi Cylix,

Before I get to the issue, I would like to thank you for the great library and your continued support and addition of new features!

I was sad to see the dropped support for the sync client, since it was the main reason I started using the library, but I've managed to make it work with a copy of the old code and some additions of sync_commit to the commands, but this isn't the problem. I had to update the library because we needed Sentinel support and your update was as if timed with our new requirement :D.

With the previous and new version I've tried to establish a redis connection after a fork, but it doesn't seem to work if there was a previous redis connection (even if terminated). For simplicity's sake and to get an idea of what I'm doing, this is the code I'm testing (the final version of it, because I've tried other things as well, which don't seem to work either), but since it uses the sync client you won't be able to compile it:

```
	cpp_redis::sync_client* redis = new cpp_redis::sync_client();

	redis->connect("127.0.0.1", 6379);
	redis->select(0);

	cout << redis->is_connected() << " get " << redis->get("test") << endl;
	redis->disconnect(true);

	delete redis;

	pid_t pid = fork();

	redis = new cpp_redis::sync_client();

	cout << pid << endl;

	cout << pid << " is_connected " << redis->is_connected() << endl;
	//cout << pid << " " << redis.get("test") << endl;

	//cout << pid << " disconnect" << endl;
	//redis.disconnect();
	cout << pid << " connect" << endl;
	redis->connect("127.0.0.1", 6379);
	cout << pid << " is_connected " << redis->is_connected() << endl;
	cout << pid << " select" << endl;
	redis->select(0);
	cout << pid << " after select" << endl;

	cout << pid << " is_connected " << redis->is_connected() << endl;
	cout << pid << " get " << redis->get("test") << endl;

	if (pid != 0)
		wait(pid);
```

The "test" key has been already pre-set in redis and I've tried lots of different configurations without pointers and disconnection and whatnot. I thought that it had to do something with destroying the instance, but it doesn't seem to work as well. The output I'm getting is: for the parent all commands are executed, but for the child the last thing printed is the " select" statement, which means that it hangs on the line `redis->select(0);`. Just to note, if no redis instance is present before the fork, the child is able to establish a connection, but it seems like something in the fork is bugging the library (reconnection and destruction don't help). While for now this was sort of ok, most of the time we need the parent to be able to have a redis connection prior to the fork and it doesn't work in any of the ways I've tried.

I would be grateful if you can look into this, since fork-ing is a rather common thing to do in multiprocess applications and to be quite frank I'm surprised that no one has reported this issue (which in the beginning led me to think that the problem was in my usage of the library, but I don't have many options left now :D ).

The ideal case would be to have an active redis connection in the parent and after fork-ing to reconnect only the child so that it has its own handler and the parent doesn't need to disconnect and connect again.

Best Regards,
Alex

**Comment by Cylix** [comment] 2017-11-05 00:24
Hi @Alejandro131,

Glad that you appreciate `cpp_redis`!

Indeed, the sync_client was removed as I wanted to only keep one final client class and one subscriber class (at some point, there were three clients, future_client, redis_client and sync_client, which was confusing for new users).
Probably right now the easiest way is to simply call any command immediately followed by a sync_commit to achieve something equivalent.
The ability to get an `std::future` if you do not specify a callback can be a good alternative too.

For the forking issue, at first sight I don't have any clue what could be the error.
I'm going to try to port your test code onto the new version to see if I can reproduce it and I will keep you up to date :)

Best!

**Comment by Cylix** [comment] 2017-11-05 00:33
Note to myself:

Was able to reproduce the issue with the following code snippet (port of test code from issue reporter to the latest version).
```cpp
#include <cpp_redis/cpp_redis>
#include <iostream>

#include <unistd.h>
#include <sys/wait.h>

using namespace std;

int main(void) {
  cpp_redis::client* redis = new cpp_redis::client();

  redis->connect("127.0.0.1", 6379);
  redis->select(0);
  redis->sync_commit();

  auto res = redis->get("test");
  redis->sync_commit();

  cout << redis->is_connected() << " get " << res.get() << endl;
  redis->disconnect(true);

  delete redis;

  pid_t pid = fork();

  redis = new cpp_redis::client();

  cout << pid << endl;

  cout << pid << " is_connected " << redis->is_connected() << endl;
  //cout << pid << " " << redis.get("test") << endl;

  //cout << pid << " disconnect" << endl;
  //redis.disconnect();
  cout << pid << " connect" << endl;
  redis->connect("127.0.0.1", 6379);
  cout << pid << " is_connected " << redis->is_connected() << endl;
  cout << pid << " select" << endl;
  redis->select(0);
  redis->sync_commit();
  cout << pid << " after select" << endl;

  cout << pid << " is_connected " << redis->is_connected() << endl;

  res = redis->get("test");
  redis->sync_commit();
  cout << pid << " get " << res.get() << endl;

  if (pid != 0)
    wait(&pid);
}
```

Switching to the following code snippet (no client defined before the fork) works fine.
Having a client defined before the fork (even without connecting it, simply new & delete) make the bug appear. 
```cpp
#include <cpp_redis/cpp_redis>
#include <iostream>

#include <unistd.h>
#include <sys/wait.h>

using namespace std;

int main(void) {
  //cpp_redis::client* redis = new cpp_redis::client();

  //  redis->connect("127.0.0.1", 6379);
  // redis->select(0);
  // redis->sync_commit();

  //  auto res = redis->get("test");
  //redis->sync_commit();

  //cout << redis->is_connected() << " get " << res.get() << endl;
  //redis->disconnect(true);

  //delete redis;

  pid_t pid = fork();

  cpp_redis::client* redis = new cpp_redis::client();

  cout << pid << endl;

  cout << pid << " is_connected " << redis->is_connected() << endl;
  //cout << pid << " " << redis.get("test") << endl;

  //cout << pid << " disconnect" << endl;
  //redis.disconnect();
  cout << pid << " connect" << endl;
  redis->connect("127.0.0.1", 6379);
  cout << pid << " is_connected " << redis->is_connected() << endl;
  cout << pid << " select" << endl;
  redis->select(0);
  redis->sync_commit();
  cout << pid << " after select" << endl;

  cout << pid << " is_connected " << redis->is_connected() << endl;

  auto res = redis->get("test");
  redis->sync_commit();
  cout << pid << " get " << res.get() << endl;

  if (pid != 0)
    wait(&pid);
}
```

From quick observation, I'm wondering if something gets wrong at the initialization of the io_service?

**Comment by Cylix** [comment] 2017-11-05 01:27
After adding some debug, seems like both thread are using the same socket file descriptor in the io_service.
I have no clue yet about what could cause this issue, but I guess that solving this weird behavior should solve this issue.

**Comment by Cylix** [comment] 2017-11-05 03:44
Ok, I understand where the bug comes from.

When you create cpp_redis instance before the fork, it initializes the default io_service instance. and stores it into a static variable.
At the moment of forking, the entire memory is copied, including static variables.
Then, each process creates a new instance and since fd starts at the same offset, both of them results in underlying tcp socket having the same fd (though referring to different sockets).
Problem is, when calling get_default_io_service, instead of creating a new instance, it reuses the instance that was previously created before the fork, leading to both process using same io_service with 2 different sockets having the same fd number.
I'll push a fix asap.

**Comment by Cylix** [comment] 2017-11-05 04:36
Pushing a fix on tacopie 926510f688f43626290d55c7847aa790ca19d07d
Once every checks/CI pass, will be integrated onto cpp_redis

**Comment by Cylix** [comment] 2017-11-05 05:05
fix has been pushed on master, I'm closing the issue.
However, if it happens the probem is still not solve, do not hesitate to re-open this issue.

Best!

**Comment by Alejandro131** [comment] 2017-11-06 11:30
Hello again,

Thank you for the quick response and fix.

Yes I understand the need to make maintenance and user flow more easy, which is why I ported the code, since the old code is heavily integrated in the system and it was easier for me to reproduce the class than to rewrite the entire project code (I just mentioned it so that you wouldn't think that I'm using an older version of the library which might have had the bug, or how did I manage to compile it with the class being removed in the current version).

Anyway the thing is that I compiled the new code, even several times and deleted everything that was in the library and include folders so that some kind of old static library isn't present, but now I still can't get this to work.

At first I thought that there was some error in my code, but If I use your first ported code (the one with a redis client instance before the fork) I get only the parent output, without anything from the child (it seems that it crashes or hangs at the constructor of the new object). This is the output:

```
1 get test
22282
22282 is_connected 0
22282 connect
22282 is_connected 1
22282 select
22282 after select
22282 is_connected 1
22282 get test
```

Could there be another problem, since I see that the compilation and everything works fine, but this is a run-time issue and can't be pin-pointed from the tests you have, or the code works for you (I'm sorry if this is something on my side)?

Best Regards,
Alex

**Comment by Cylix** [comment] 2017-11-08 04:39
Reopening that, I'll have a look

**Comment by Cylix** [comment] 2017-11-08 07:32
OK, curious I didn't catch that before.
The problem is quite complex and due to mixing threads and fork.
Basically, when forking and re-creating a new io_service in the child, the destructor of the old io_service is called and tried to join threads. std::thread::joinable returns true because memory has been fully copied, but the child process only has one thread and it crashes when calling join.

As a working solution, I'll revert change of yesterday and instead allow set_default_io_service to take nullptr as a parameter (right now, nullptr is ignored).
Calling set_default_io_service(nullptr) before the fork and after deleting all instances of redis connections would allow to safely fork without any residual thread under the hood.

**Comment by Cylix** [comment] 2017-11-08 07:39
I pushed the fix on master, can you retry and keep me up to date?

Here is my new test code: 
```cpp
#include <cpp_redis/cpp_redis>
#include <iostream>
#include <tacopie/tacopie>

#include <sys/wait.h>
#include <unistd.h>

using namespace std;

int
main(void) {
  cpp_redis::client* redis = new cpp_redis::client();

  redis->connect("127.0.0.1", 6379);
  redis->select(0);
  redis->sync_commit();

  auto res = redis->get("test");
  redis->sync_commit();

  cout << redis->is_connected() << " get " << res.get() << endl;
  redis->disconnect(true);

  delete redis;
  tacopie::set_default_io_service(nullptr);

  pid_t pid = fork();

  redis = new cpp_redis::client();

  cout << pid << endl;

  cout << pid << " is_connected " << redis->is_connected() << endl;
  //cout << pid << " " << redis.get("test") << endl;

  //cout << pid << " disconnect" << endl;
  //redis.disconnect();
  cout << pid << " connect" << endl;
  redis->connect("127.0.0.1", 6379);
  cout << pid << " is_connected " << redis->is_connected() << endl;
  cout << pid << " select" << endl;
  redis->select(0);
  redis->sync_commit();
  cout << pid << " after select" << endl;

  cout << pid << " is_connected " << redis->is_connected() << endl;

  res = redis->get("test");
  redis->sync_commit();
  cout << pid << " get " << res.get() << endl;

  if (pid != 0)
    wait(&pid);
}
```

Basically, same as before, but now I call `set_default_io_service(nullptr)` after deleting the cpp_redis instance.

Best

**Comment by Alejandro131** [comment] 2017-11-08 09:05
Thank you for the quick response and fix.

I downloaded the latest version and tested with the additional line and now everything works!

I'll probably add that line in the destructor of the overloaded classes I have so that I don't forget it when using them.

Best Regards,
Alex

**Comment by Cylix** [comment] 2017-11-08 20:52
Awesome!

Closing this issue then, do not hesitate to reach out to me if you got any other issues or questions in the future.

Best

**Closed by Cylix** 2017-11-08 20:52 UTC
Labels: bug, unix, windows
