### ISSUE TITLE
Disconnect issue

### ISSUE THREAD

**Issue by tobbe303** [Cylix/cpp_redis#4] opened 2015-11-27 10:30 UTC
There is a disconnect issue in the examples that puzzles me. The sigint_handler and the subsequent disconnection handler are invoked upon sending the interrupt signal, but the main function does not terminate.

Adding a sleep(1) inside the "while (not should_exit);" loop appears to solve the termination issue, but is there possibly a disconnect/threading issue at play here?

Thank you for a nice Redis client!

**Comment by Cylix** [comment] 2015-11-27 10:41
On which example: redis_client, redis_subscriber or both of them?

**Comment by tobbe303** [comment] 2015-11-27 10:43
Both of them. Using g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4.

**Comment by Cylix** [comment] 2015-11-27 10:53
Mmh, if it was only in the redis_subscriber, the problem may have been caused by a compiler optimization because the `should_exit` variable is not marked as `volatile` (unlike in the redis_client example): because the loop is empty, the compiler sometimes optimizes the loop to a simple `while (true)` without the need to access the value of should_exit.

But if it is on both examples, then I will need to check my implementation.

Does it happen every time?

**Comment by tobbe303** [comment] 2015-11-27 11:24
Yes, it happens every time on my machine in both examples. I've also tried volatile etc. but no avail so far.

I also notice the main thread appears to get suspended upon disconnection. If I output the should_exit value to stderr inside the loop I notice the output stops.

**Comment by Cylix** [comment] 2015-11-27 12:19
Ok, I finally manage to reproduce the issue. It never happens on my mac, but I got it sometimes (maybe 10% of the time) on a debian VM.

I've localised the issue in the [tcp client](https://github.com/Cylix/cpp_redis/blob/master/sources/network/tcp_client.cpp#L66).

It's a similar problem that the one reported in #3: sometimes the conditional variable is locked after having been notified by the other thread.

I should patch it this evening if I have the time.

**Comment by Cylix** [comment] 2015-11-27 18:03
I've added atomic variables to avoid waiting if conditional variable has already been notified.
After this modification, I'm not able to reproduce the issue on my computer.

Could you please tell me if everything is ok now? Or if the problem is still there for you?

**Comment by tobbe303** [comment] 2015-11-28 06:09
The redis_client example is working now, but the redis_subscriber example still hangs on interrupt. However, making the should_exit variable in this example volatile std::atomic_bool (which is the type the redis_client uses) seems to do the trick!

Thanks!

**Comment by Cylix** [comment] 2015-11-28 10:17
Oh, yes, I've forgot to commit this! This is now done, I close the issue.

Thank you again for your help :)

**Closed by Cylix** 2015-11-28 10:17 UTC
