### ISSUE TITLE
cmake install rules break buildroot

### ISSUE THREAD

**Issue by FrankLorenz** [Cylix/cpp_redis#120] opened 2017-10-17 12:41 UTC
I currently try to add cpp_redis as a buildroot package to our environment. 
I stumbled across an issue that buildroot stops during the installation with the following error:
`cpp_redis 4.1.0 Fixing libtool files`

`cpp_redis: installs files in /home/lorenz/projects/xenon/buildsystem/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot//home/lorenz/projects/xenon/buildsystem/output`
`make[1]: *** [package/pkg-generic.mk:276: /home/lorenz/projects/xenon/buildsystem/output/build/cpp_redis-4.1.0/.stamp_staging_installed] Fehler 1`
`make: *** [Makefile:79: _all] Fehler 2`

You see that buildroot complains about the odd directory structure that puts an absolute path to buildroot output directory below the `sysroot` directory.
After some investigation I figured out that this is caused by the following 2 lines inside CMakeLists.txt:
`install(DIRECTORY DESTINATION ${CMAKE_BINARY_DIR}/lib/)`
`install(DIRECTORY DESTINATION ${CMAKE_BINARY_DIR}/bin/)`

I wonder if this is really what is intended because `${CMAKE_BINARY_DIR}/lib/`points to the `lib` subdirectory in the build directory, so cmake tries to "install" into the build directory here.
Furthermore (I do not understand why up to now), buildroot interprets this and creates the lib and bin directory inside `[...]/sysroot//home/lorenz/projects/xenon/buildsystem/output` and then exits with error.

I can build successfully when I comment out the two lines.

**Comment by Cylix** [comment] 2017-10-21 09:21
Hi,

I recently merged a PR changing these two lines to use some other CMake variables: https://github.com/Cylix/cpp_redis/pull/119/files
Maybe it fixes your issue?

If not, would you mind sharing an example of how to trigger that bug?
I tried on my side but could not reproduce it.

Best

**Comment by Cylix** [comment] 2017-11-13 01:43
Hi,

In the absence of a response, I'm closing this issue.
However, feel free to re-open it if necessary.

Best

**Comment by FrankLorenz** [comment] 2017-12-18 09:00
First, I did not realize that the issue with the two lines in `CMakeLists.txt` is in both cpp_redis and tacopie.
These two lines are definitely the ones that cause the trouble. If they are present in cpp_redis' or tacopie's `CMakeList.txt`, the build fails. If they are removed, the build succeeds.
I still wonder what these lines are good for and if they can be removed.

**Comment by Cylix** [comment] 2018-02-09 06:51
Hi,

Sorry for the very long time to process this issue.
This is now fixed thanks to #159 (cpp_redis) and e8eaad3 (tacopie).

I'm closing this issue but do not hesitate to re-open it if necessary.

Best

**Closed by Cylix** 2018-02-09 06:51 UTC
